[book]
authors = ["CompEng0001"]
language = "en"
multilingual = false
src = "src"
title = "Advanced Computer Engineering"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true

[preprocessor.pagetoc]
[output.html]
mathjax-support = true
input-404 = "404/404.md"
git-repository-url = "https://github.com/uniofgreenwich/ELEE1119_Exercises"
edit-url-template = "https://github.com/uniofgreenwich/ELEE1119_Exercises/edit/main/{path}"
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]


[output.html.print]
enable = false
